# Generated by Django 3.2.4 on 2021-06-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='evidencija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predmet', models.CharField(max_length=30)),
                ('datum', models.DateField()),
                ('oblik', models.CharField(max_length=50)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('broj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_korisnika', models.CharField(max_length=30)),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('dekan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='kuca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osoblje', models.CharField(max_length=30)),
                ('datum', models.DateField()),
                ('oblik', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('profesor', models.CharField(max_length=30)),
                ('asistent', models.CharField(max_length=30)),
                ('semestar', models.CharField(max_length=30)),
                ('termin', models.TimeField()),
            ],
        ),
    ]
