# Generated by Django 3.2.4 on 2021-06-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predmet',
            name='termin',
        ),
    ]
