# Generated by Django 3.2.4 on 2021-06-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0002_remove_predmet_termin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='dekan',
            field=models.CharField(max_length=30),
        ),
    ]
