# Generated by Django 3.2.4 on 2021-06-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0003_alter_korisnik_dekan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='korisnik',
            old_name='dekan',
            new_name='oblik',
        ),
    ]
