# Generated by Django 3.2.4 on 2021-06-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0004_rename_dekan_korisnik_oblik'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='status',
            field=models.CharField(default='Nije aktivan', max_length=30),
        ),
    ]
