# Generated by Django 3.2.4 on 2021-06-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0005_korisnik_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='stil',
            field=models.CharField(default='Standardna', max_length=30),
        ),
    ]
