# Generated by Django 3.2.4 on 2021-06-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0006_korisnik_stil'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencija',
            name='weekday',
            field=models.CharField(default='', max_length=20),
        ),
    ]
