# Generated by Django 3.2.4 on 2021-07-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0007_evidencija_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuca',
            name='status',
            field=models.CharField(default='Nije obrađeno', max_length=30),
        ),
    ]
